language: python
python: '2.7'
install:
- pip install -r requirements.txt
- pip install nose
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: GYGwBDut7XFMyj6kx83/IvEX4hSntZlROeokLGjqqKQRqOBP2f+n1jmh59UX/f+bYHqMsvm/CGj1k2Prxv7e2fzXf/+k/Th0aabfeG0cV4Ruo1MSo//MwxJyth1GFOte6cwrcYWziwCMCZHtA5297nWh1gzgvJYF6r/MbBfWbNs=
  app: vine-thumbnails
  on:
    repo: grampajoe/vine-thumbnails
