language: python
python: '2.7'

install:
  - pip install -r requirements.txt
  - pip install nose
script:
  - nosetests

deploy:
  provider: heroku
  api_key:
    secure: aoHFxEGIZINM71e6rVLwZaTxInE3tX2KuoYpKd9iT8JW2Yp0KO8ax7UHVr7tPiiGgAGXKykVw4IHJdePJp0TzTaSg/T+EEZJaZHd05h4XLQVbe1LrZ38yPdU20cllylblKxLh11dN70JBuEuC89Z8BpQ0fDUuEQMOBsIzZeXoAs=
  app: vine-thumbnails
  on:
    repo: grampajoe/vine-thumbnails
