language: python
python: '2.7'
install:
- pip install -r requirements.txt
- pip install nose
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: f0YFuk6pwtuRzwTZvTJZdg/aSBjy/+sqM9q2OScAkzo2rb6KP58lAzzvPfB6y9I+BDNRU3u9Vayf55+4blM3FMR0VdQfDeZHuGZFdq6mZevOZ6Y9bCHYHH7t84WgDN53mk157KNvwqrgb0STjjtrwlok3KUJ9WKb6hk3JreqsbE=
  app: vine-thumbnails
  on:
    repo: grampajoe/vine-thumbnails
